title: One hour
author: airrrider
email: 
description: > # this means to ignore newlines until "baseurl:"
  Take an hour and work on it till the time runs right.  Repeat when you want.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
